---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freshrss
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: freshrss
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
  values:
    image:
      repository: linuxserver/freshrss
      tag: version-1.17.0
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        tls:
          - hosts:
              - "rss.${DOMAIN}"
        hosts:
          - host: "rss.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
