---
collections:
  - name: community.general
    version: 7.0.1
  - name: community.sops
    version: 1.6.5
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.10.3
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.1
  - name: geerlingguy.nfs
    src: https://github.com/geerlingguy/ansible-role-nfs
    version: 2.0.0
  - name: githubixx.cilium_cli
    version: 2.6.0+0.13.2