---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: stash
  namespace: stash
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.appscode.com/stable/
      chart: stash
      version: v0.11.8
      sourceRef:
        kind: HelmRepository
        name: appscode
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    operator:
      registry: appscode
      repository: stash
      tag: v0.11.8
  valuesFrom:
    - kind: Secret
      name: "stash-helm-values"
