---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - adguard
  - cert-manager
  - external-dns
  - ingress-nginx
  - k8s-gateway
  - metallb
  - oauth2-proxy
