---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  # - adguard
  - cert-manager
  - cloudflared
  - external-dns
  - ingress-nginx
  - metallb
  # - oauth2-proxy
