---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: bitwarden
spec:
  interval: 5m
  createNamespace: true
  chart:
    spec:
      chart: bitwardenrs
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-external
      namespace: kube-system
  values:
    image:
      repository: bitwardenrs/server
      tag: 1.16.3
    persistence:
      enabled: true
      storageClass: nfs-kube
  valuesFrom:
  - kind: Secret
    name: "bitwarden-helm-values"