apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bitwarden-helm-values
  namespace: bitwarden
spec:
  encryptedData:
    values.yaml: AgC6IEkiFZhOpBQ1cstkTnzaS3370GAMjIoyz0CBPKuX0P0IbfPox7tmOMojfdNRAVwPAtKv3gemiIwBahtKonQ6zlSMO19Ar15l2Qfm4v1did1aszOLqu07M18e4WeOeGRfaa/sTL7LKb0P+ohRa+ug0RZWzNzcCTQoozzRvnUYS8UteUN43kcDaj6wzwoAcvEc2QjGthb3+jgmmJSA7W1xMFgz5izBBHTDG5VP0KHSY7hV3DvVFqWjBRWg+93aSDSvC70u9SCqPq1Tf0pBd9xPeI7sD+XG1rnJNJHG6zsurSlPDcrJ2WOnq2WhPfE4K5mAuQmKW1BWTrkyRZdN8O9PiiqxeRWdKAAMso9gGqSoKIoqUNG24J8CQz867tCSsCc4J2J+FaL+VGp20b86VMt7nNGD2e3L8jVYmZsxK7rgPK3C05s41W0b+zrj0Zsr1Zj+3V4jdUTvHZe/Jjct3AkOvaXg19N4dcTTInPtrRWFJ5MhpMtKyfoGvuv5BLjtTl6AuFXvhLzuWZNa7jJfi+hPHIIqbC1G/hY59jEg8n6QvuXhNqGokEo/5zFVYQtCUnnl7VmbBMzNJoq8RZsVJ11fgFbaW/2wOTX/bktd3Hoe2s/+DfmF5afK27fn1pAUbLMyh2lhqkaWTJbdONbe59B2cXYCHcDbKqij/k0onqLIACKWwQ5MFQKZpue9cPOS5YeTtSkAgpFY1uYoN7N+N6yzhwcctBCRzPbMNN+lDYVv37mwP/aCaPItOtu4WmsbXvr2ZuQIMAEWhsvDS1QtC4yrosylMb5uC10bqStQdWETQhaQWejXag6NlAydWPUNp9F6TwOm7KIV4XZphWtn5g8D0GHf+WoJ2ZcNSco9iFaVG1LJ16CWAs8DG1VZpC/+VnPKZP8oNff3Tl3nVy0a1kZw5xyMaPKZWahFH8XZEZrZAS2eOJjFhoXIx1J6jarzfQj7mRyf5RWew++0NhENe/6hDDtbQ0r1pLpp155/onCvGTX0E30+DFq/NdtTkXqy5JhQFAlRGmVVPBk=
  template:
    metadata:
      creationTimestamp: null
      name: bitwarden-helm-values
      namespace: bitwarden
