---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: mariadb
      version: 12.2.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: metallb
      namespace: networking
  values:
    image:
      repository: bitnami/mariadb
      tag: 10.11.3-debian-11-r0
    auth:
      rootPassword: "${MARIADB_ROOT_PASSWORD}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    primary:
      name: primary
      persistence:
        enabled: true
        storageClass: nfs-kube
      service:
        annotations: {}
        type: LoadBalancer
        loadBalancerIP: "${MARIADB_PRIMARY_LB_IP}"
    secondary:
      name: secondary
      replicaCount: 1
      persistence:
        enabled: true
        storageClass: nfs-kube
      service:
        annotations: {}
        type: LoadBalancer
        loadBalancerIP: "${MARIADB_SECONDARY_LB_IP}"
