apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: node-red-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgANKGTDuVQqePexvRMou/KwbxI3vw3SFswpRXSikSt119rO3lpPW5uJDU3rh0bw9L2ynaKj6PEHB/Vu+fhkrJ8ifCOY6JUPC/n36toRbhJoPavVpEiwmlKsbaWl4L5hMCWaO5xHGYC0rvHOKQLXbIsQygAen9BxD0+VzG3I/RmF5dLZgqoKy6ltF/ltKkNtFHFT7PQbxKGEl0P5UjTykoa56k47bzekvACwjWwuWww8pjCnWyzJcmB/I2qGi/lPwSCAD4snI3sQCc2Jc4WztiEa8Qghz0s6nsjgNmzI6SSSJM1diOgf5Zc7SdDKIRMpgmN5AQglJPTZ+IKNGaVDBKfwErt9gBijFDa3fRlUxodjSYtPV1/oeDNwLDvcsJM68GNyFJBx2M6Utz45R1c7SlC7ptX3IneNHi6T4iZ9HSZz7dwm8Me791oBILmDgbxbWacdtEJOCB9rViy0vhZmAvjlQ/4XxNY/KyTso0tdqWayGrXOAMqcZJvldZS1AXOG0DkW6ieTY5ClBJicy7VHHdQPta/EwhQF8cJm2xxVMxuIWL0Uyl/C5odfQbPhUeClw5G/q+yIvqlU1qr9MDATDJJBZDnbZBT8wpcJG/Meak4+VQ/HnUEyKD71thxjdUw0RJDfpGmFOdd5WgnMY17Vy2JLyqze5axI0DQMmLsnV0ODui5ol/vGxLxAm/n53JYan1Qwbf6rNh+zbu/IjSAJYD/RW308I+UXlrB8IFJMCRADAZtBGKVs118CKVMPnTpJ2t2A8B9+Sm1K1B4REeZDlfGbJ/yTvrEZZtXJuo82w7OnZ8R1+pQPr8uETwudESGapVmF2UIoaelLHa89L8pTSwe0gYw/NOPGFrKDHrlQz6xYakfs1w==
  template:
    metadata:
      name: node-red-helm-values
      namespace: default

