---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-external
      namespace: kube-system
  values:
    enableProjects: true
    timezone: America/Chicago
    persistence:
      enabled: true
      storageClass: nfs-kube
  valuesFrom:
    - kind: Secret
      name: "node-red-helm-values"
