---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: calibre-web
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /export/Calibre-Web
    server: 192.168.1.105
  storageClassName: calibre-web
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: calibre-web
  volumeMode: Filesystem
