---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://vmware-tanzu.github.io/helm-charts
      chart: velero
      version: 2.14.4
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
  values:
    image:
      repository: velero/velero
      tag: v1.4.2
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:main
        volumeMounts:
          - mountPath: /target
            name: plugins
    restoreResourcePriorities: persistentvolumes
    logFormat: json
    backupsEnabled: true
    snapshotsEnabled: false
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "120h"
  valuesFrom:
    - kind: Secret
      name: "velero-helm-values"
