---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.6.14
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.12.1
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.12.1
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - "${METALLB_LB_RANGE}"
    prometheusRule:
      enabled: false
