---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: metallb
      version: 4.1.16
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    controller:
      image:
        repository: bitnami/metallb-controller
        tag: 0.13.9-debian-11-r3
    speaker:
      image:
        repository: bitnami/metallb-speaker
        tag: 0.13.7-debian-11-r3
