apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:gDcs0Qax2AQUNYcWzxI/MFOMET1Ey5Bhg6KtL6PVNSy3lhBg,iv:CM/RfvqUL6pw6/cgdz0+5RI65RQtvX7XkFbajGFkdJA=,tag:mCyIzjpe/mEhCqKg6vtb0Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:zN4uztVJ4ROXxqskj88PtQoBFBnyJWyAYHEGBCtgi3dYTqUXik2nwNr+g6XL8WwaW06j5lr4ZWHdkdhCDoX0l0MFUd79DJmtTt0yOji7CplgbGxrfZIuqfCcetuAHKHxPHt53yOZMObT2eoqKaHGi8sQ4RpgB9t4Gvnbg3Zf1F86Zd3q9GSu+uXigkwnfU/0uP8ji25Ates2hgb6dejLi3zQL30rBSraS8g0gK+ZfQ==,iv:rHbd43+dMG0ZTWZqosplvPQfoLcyQFC7MhRtXzk9mE8=,tag:kFYKvVbUIgfox1bCW44V+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19kk4xalns9ftcul3a9wmnfur79fsqdkrq93mwyy84lj3etzm89squaxfcz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1REpnUDJ0cldmdXF2K1pY
            Um9Wd3Z1YUNheUoyaGU1OWE5OWZQN2R1aUFvCk8vODkzNHVLa0FXTXgvbG44MmxH
            akd1NHM4T0k4WGR3NU9jNTd6ZnEya2MKLS0tIC9tNGp2c3dsMElIdk1qeCtReEw0
            VHFpN2NwWlgyWFFMKzJuLzJ6SEpRUjAKmW34Z9Nisz1p6COqdNcEfWpWPxLa4S0+
            AglnoSAByaBEJ0iKf4zIooLDoTndJS1Hh6PycJ0ySNuUUEjtjatRpA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T12:25:47Z"
    mac: ENC[AES256_GCM,data:1tEYfs3EpPDXVjddPHquI4Gyk6EQidc4f4hi+BqrGRUhEzWZ0AN51XcPbpv4gP4PIgUxbhwjNi6Iwp+2npj8rAIrdFk+Fa/+r0wGtRBZm7o4iOUnAqYqtCLB/dxWkJAfziPxGaiEpTndynJ9W2Ch/SpEAHE+SpgV6CfHAx0o2ww=,iv:vUpu5zriX5fe9uOZShR9/x9iBwO104BSQcinU7RUNYQ=,tag:eUQQoGDTPhKC4loxcwd5RA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
