---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb-address-pools
  namespace: networking
spec:
  interval: 10m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: metallb
      namespace: networking
  values:
    resources:
      - apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: default
          namespace: networking
        spec:
          addresses:
            - "${METALLB_LB_RANGE}"
      - apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: metallb-l2advertisement
          namespace: networking
        spec:
          ipAddressPools:
            - default
