---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grocy-helm-values
  namespace: grocy
spec:
  encryptedData:
    values.yaml: AgBVSadXbmZZHEw6c/XGnPhUgCyfICGpjXA7sQp9nDd/ARd+KpsjTZFAwAeqctCM+JzJcq5xjXqF9dfKkVwdKXCkYUKazzB2rOdZ3rkV8gaHAfiLf9F2OmpjYapokAFdd0ZQOU7OJcoKlrq2EiDAcMwUXJ6maMxyc9xHjtRiWg+Brw+Yw0QtvAIU6VidSzK1zgLYgTKNr6NiOPnMu+HhiH+3VKin9IdLSVHX+PmaBGM2QimyGrdo+CQUaGqJhfHUSioTrHe9QZ3IGVSYSEjhJNkjODzwKSwXARo5QtLc7FQaGviTmQy6P2oB/EnNBkqzh46AHyO9FXDBKdwyNcAgemh0AVEc2TR+C+nTRRSs3zo+8sV+r3+gXE92sTOouk8b8n0Xh8MtXQzpVkvGKhyOQkzBj/rQZAjlZZymJhkxZ22AK6RXatGTzq/BJzbQpqokNRf/rZqbofWV/2auxxRkczTn/W64z+NhioIHtzwTEWc8vRUSjQJz3J4RLoSC/3kewPLDitv2p5qDR4aDBjgO0XwSRI+R3EiFqxIBODdwfl+vnB3YmbXyhS9SleS9QcWECl/AMqYXOJ65DoblCXzbgzny9uZItfrW0cjVtn8bT0Ie20DmSuTvXbpGFNZYaA5hBVdw66BOZLLnu9yv/VBm/8a3jJ2r1t8VDDYeW+GfWjf6ZOZ0NBP3oGIh4r9d0svSdW8rdhOG2HXHUHldKlhr8sFhMPaKfqnzUlTQ3kWIDe85oahoLh5B52trIjh6zoBwFyX+abuTKuSyzfw/GInTp6oeFE+FryUTd2+E4GJF7YJrdIEOaHn6O4Z4EaTLLil1momNNki14g3z7anUHwsMqr9pJkebkh/WEz3gMpwDOYvafV19VBc53F0v6C3L8BCiZFDOjeltzvNpL8uRR8bpURH+NhGrqW04dbaEFGC4+6XpCLs5
  template:
    metadata:
      creationTimestamp: null
      name: grocy-helm-values
      namespace: grocy
