---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  releaseName: cert-manager
  helmVersion: v3
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.1
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        # enabled: true
        interval: 60s