---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
  annotations: 
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~1.0.0
    filter.fluxcd.io/webhook: semver:~1.0.0
    filter.fluxcd.io/cainjector: semver:~1.0.0
spec:
  releaseName: cert-manager
  helmVersion: v3
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.0.1
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        # enabled: true
        interval: 60s