---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: v1.0.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        # enabled: true
        interval: 60s