---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /export/Home-Assistant
    server: 192.168.1.105
  storageClassName: home-assistant
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: home-assistant
  volumeMode: Filesystem
