---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: "${NFS_BASE_PATH}/Apps/home-assistant"
    server: "${NFS_SERVER_IP}"
  storageClassName: home-assistant
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: home-assistant
  volumeMode: Filesystem
