---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: k3s-gitops
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/RickCoxDev/k3s-gitops

