---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hajimari
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      chart: hajimari
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: hajimari
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    hajimari:
      name: "Rick"
      defaultEnable: false
      showAppGroups: true
      showAppUrls: false
      alwaysTargetBlank: true
      showGlobalBookmarks: true
      showAppStatus: false
      namespaceSelector:
        matchNames:
          - home
          - networking
          - media
          - monitoring
      customApps:
        - name: OctoPi
          url: http://192.168.1.116
          icon: printer-3d
      globalBookmarks:
        - group: Second Brain
          bookmarks:
            - name: Notion (Desktop)
              url: "notion://"
            - name: Notion (Web)
              url: "https://notion.so"
            - name: Obsidian
              url: "obsidian://"
            - name: Readwise
              url: "https://readwise.io/"
            - name: Reclipped
              url: "https://reclipped.com/"
            - name: Instapaper
              url: "https://www.instapaper.com/"
        - group: K3s Cluster
          bookmarks:
            - name: Github Repo
              url: "https://github.com/RickCoxDev/home-cluster"
            - name: NameCheap
              url: "https://www.namecheap.com/"
            - name: Auth0
              url: "https://auth0.com/"
            - name: Cloudflare
              url: "https://www.cloudflare.com/"
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: "hajimari.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hajimari.${DOMAIN}"
            secretName: hajimari-tls
    persistence:
      data:
        enabled: true
        storageClass: nfs-kube
