---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      version: 4.0.6
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    controller:
      name: controller
      image:
        registry: k8s.gcr.io
        image: ingress-nginx/controller
        tag: "v1.0.0"
      config:
        ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        use-proxy-protocol: "false"
        proxy-body-size: "100m"
        use-forwarded-headers: "true"
        forwarded-for-header: "CF-Connecting-IP"
        # Cloudflare IP Addresses - Used to forward the real client IP address to the backend service
        # https://www.cloudflare.com/ips/
        proxy-real-ip-cidr: "103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/12,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
        # whitelist-source-range: "103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,104.16.0.0/12,108.162.192.0/18,131.0.72.0/22,141.101.64.0/18,162.158.0.0/15,172.64.0.0/13,173.245.48.0/20,188.114.96.0/20,190.93.240.0/20,197.234.240.0/22,198.41.128.0/17,2400:cb00::/32,2606:4700::/32,2803:f800::/32,2405:b500::/32,2405:8100::/32,2a06:98c0::/29,2c0f:f248::/32"
        # enable-modsecurity: "true"
      ingressClassResource:
        name: external
        enabled: true
        default: false
        controllerValue: "k8s.io/ingress-nginx"
      publishService:
        enabled: true
      extraEnvs:
      - name: TZ
        value: America/Chicago
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"
      kind: Deployment
      nodeSelector:
        beta.kubernetes.io/os: linux
      service:
        enabled: true
        annotations:
          metallb.universe.tf/address-pool: default
        externalIPs:
          - "${EXTERNAL_INGRESS_NGINX_LB}"
        loadBalancerIP: "${EXTERNAL_INGRESS_NGINX_LB}"
        loadBalancerSourceRanges:
          - "${EXTERNAL_INGRESS_NGINX_LB}/32"
        enableHttp: true
        enableHttps: true
        targetPorts:
          http: http
          https: https
        type: LoadBalancer
        internal:
          enabled: false
      admissionWebhooks:
        annotations: {}
        enabled: true
        failurePolicy: Fail
        port: 8443
        certificate: "/usr/local/certificates/cert"
        key: "/usr/local/certificates/key"
        service:
          annotations: {}
          # clusterIP: ""
          externalIPs: []
          # loadBalancerIP: ""
          loadBalancerSourceRanges: []
          servicePort: 443
          type: ClusterIP
        patch:
          enabled: true
          image:
            registry: k8s.gcr.io
            image: ingress-nginx/kube-webhook-certgen
            tag: v1.0
          nodeSelector:
            beta.kubernetes.io/os: linux
      metrics:
        enabled: false
        service:
          annotations: {}
          # prometheus.io/scrape: "true"
          # prometheus.io/port: "10254"
          externalIPs: []
          # loadBalancerIP: ""
          loadBalancerSourceRanges: []
          type: ClusterIP

        serviceMonitor:
          enabled: false
          namespace: ""
          scrapeInterval: 30s

        prometheusRule:
          enabled: false
          rules: []
            # # These are just examples rules, please adapt them to your needs
            # - alert: NGINXConfigFailed
            #   expr: count(nginx_ingress_controller_config_last_reload_successful == 0) > 0
            #   for: 1s
            #   labels:
            #     severity: critical
            #   annotations:
            #     description: bad ingress config - nginx config test failed
            #     summary: uninstall the latest ingress changes to allow config reloads to resume
            # - alert: NGINXCertificateExpiry
            #   expr: (avg(nginx_ingress_controller_ssl_expire_time_seconds) by (host) - time()) < 604800
            #   for: 1s
            #   labels:
            #     severity: critical
            #   annotations:
            #     description: ssl certificate(s) will expire in less then a week
            #     summary: renew expiring certificates to avoid downtime
            # - alert: NGINXTooMany500s
            #   expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"5.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
            #   for: 1m
            #   labels:
            #     severity: warning
            #   annotations:
            #     description: Too many 5XXs
            #     summary: More than 5% of all requests returned 5XX, this requires your attention
            # - alert: NGINXTooMany400s
            #   expr: 100 * ( sum( nginx_ingress_controller_requests{status=~"4.+"} ) / sum(nginx_ingress_controller_requests) ) > 5
            #   for: 1m
            #   labels:
            #     severity: warning
            #   annotations:
            #     description: Too many 4XXs
            #     summary: More than 5% of all requests returned 4XX, this requires your attention

    ## Default 404 backend
    defaultBackend:
      enabled: false
      name: defaultbackend
      image:
        registry: k8s.gcr.io
        image: defaultbackend-amd64
        tag: "1.5"
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
      serviceAccount:
        create: true
        name: ""
        automountServiceAccountToken: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      service:
        annotations: {}
        externalIPs: []
        # loadBalancerIP: ""
        loadBalancerSourceRanges: []
        servicePort: 80
        type: ClusterIP
