apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: node-red-helm-values
  namespace: node-red
spec:
  encryptedData:
    values.yaml: AgClNtbujvTfQ9bbbBVBlsy9+Q2b27LH5KizFZ6GzUszDaXJcwrpP9Cq/fEfGq5q+yXVWMrBps98iANVB3a3Ie3RQtVp7uLrXaOf/lCAEbsQDXIvuzVJPoJlif2RESSGy2PcYfnuo+jsn0qhGn9LuT4AzBCTdPvSK1msiuyDUDdYd6+VZyvAEHqQn45fRXhOmRKt00fr2BwfJeb5nTUcujC5tI90K8cnvjCe3r+oRk+1OlnB28rWfxbIDEvKRhAq26RJjTuGJNrzuJwnve3ZgF8j++aSEVOQiuy0x0IjltAT9IHVnZIQRfyGhcyrao9/flowN41uWEnab8m88ZTMNT0l5ey8jTRZxhoJK27VboS8tzOxdmdMyx1yzD+IOlY+ybCJxdlhLMtQqzexzs+gZ2E/6rnmdbyji6FjW/UQ1TvSL4NrlCZP3aO6aGmBEIfBhy4hwTyu5SYeJj1t1ucix7Uiph1rjWJIo2mJDQi5MtM5ID5BudFiZT+EgsMZ9z3WrclvLqImbQyRbGY1fKbHx6Mwa52pKNAGHdjY6G/jlQnWlGpcivb5egtI/C8jyaOgsSVa/ZH0ICkmeDxYevBBxnznGMYKoH2uP4pcHtSoiZetlSqp9Kz8Jiqm7yz4iaAOx7k+R7TAYkeZ7MArCtD9KUFj6zC0FNRuyah9347pj2hM0DRe5Do3mdLjgzZSWkh1UihfLdl0kHmuTER0LsZoEbOuKux7y0iVBt+QPagalbWcZS2rHWyBQYxAHkqPv1+zv9TcjA1NvekO4/TzJCmeeIMZR4TT+qpMcIIxSK2mNsmTS4aZaL33nOk+FJFrdJAmSDrKxmY9emaHSmb14WbLMM8qFtoUiWXI1cTYwwX7eJq+wQVGuoVtjlnplhDMbkmPqxAeyQvIcS5REmJAyTscY7EwPjft3ZU15/7C5EuYP1YHzw89cFK7/lydHqdevUSzwZTUNOTFkauhJ2b4vrl3lFsXPvinQIQ1Aq5TmTQN3YfcXjZM5q2dn0qyRupvnN5LTtsbPkPbN74IcgxMbwL+x562c+qz
  template:
    metadata:
      creationTimestamp: null
      name: node-red-helm-values
      namespace: node-red
