---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobooks
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: "${NFS_BASE_PATH}/AudioBooks"
    server: "${NFS_SERVER_IP}"
  storageClassName: audiobooks
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: audiobooks
  volumeMode: Filesystem
