---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: "${NFS_BASE_PATH}/Movies"
    server: "${NFS_SERVER_IP}"
  storageClassName: movies
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: movies
  volumeMode: Filesystem
