---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: podcasts
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: "${NFS_BASE_PATH}/Podcasts"
    server: "${NFS_SERVER_IP}"
  storageClassName: podcasts
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcasts
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: podcasts
  volumeMode: Filesystem
