---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-shows
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  nfs:
    path: /export/TV-Shows
    server: 192.168.1.105
  storageClassName: tv-shows
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-shows
  namespace: media
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: tv-shows
  volumeMode: Filesystem
