apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik-external
  namespace: kube-system
spec:
  releaseName: traefik-external
  helmVersion: v3
  chart:
    repository: https://containous.github.io/traefik-helm-chart
    name: traefik
    version: 9.1.1
  values:
    ingressRoute:
      dashboard:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik-internal
    providers:
      kubernetesCRD:
        enabled: false
      kubernetesIngress:
        enabled: true
        publishedService:
          enabled: false
    additionalArguments:
      - "--providers.kubernetesingress.ingressclass=traefik-external"
      - "--api.dashboard=true"
      - "--api.insecure=true"
    logs:
      general:
        format: json
        level: ERROR
    access:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 192.168.1.11