apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /export/FreshRSS
    server: 192.168.1.105
  storageClassName: freshrss
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: freshrss
  volumeMode: Filesystem
