---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    controller:
      image:
        repository: metallb/controller
        tag: v0.9.5
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9.5
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.10/31
        - 192.168.1.12/30
        - 192.168.1.16/30
        - 192.168.1.20/32
    prometheus:
      enabled: true
      serviceMonitor:
        # enabled: true
        interval: 30s
      prometheusRule:
        enabled: false
