---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: storage
spec:
  interval: 10m
  chart:
    spec:
      chart: velero
      version: 2.32.3
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    image:
      repository: velero/velero
      tag: v1.10.0
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.2
        volumeMounts:
          - mountPath: /target
            name: plugins
    backupsEnabled: true
    snapshotsEnabled: true
    deployRestic: true
    upgradeCRDs: true
    metrics:
      enabled: false
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: true
    credentials:
      useSecret: true
      name: velero-s3-keys
      secretContents:
        cloud: |
          [default]
          aws_access_key_id=${B2_VELERO_ACCESS_KEY}
          aws_secret_access_key=${B2_VELERO_SECRET_KEY}
    configuration:
      provider: aws
      logLevel: info
      logFormat: json
      backupStorageLocation:
        name: default
        bucket: mysmarthome-backup
        config:
          region: us-west-002
          s3Url: https://s3.us-west-002.backblazeb2.com
      volumeSnapshotLocation:
        name: default
        provider: aws
        bucket: mysmarthome-backup
        config:
          region: us-west-002
    schedules:
      daily-backup:
        disabled: false
        # Everyday at 3am
        schedule: "0 3 * * *"
        template:
          # keep for 7 days
          ttl: "168h"
      weekly-backup:
        disabled: false
        # Every Sunday at 12am
        schedule: "0 0 * * 0"
        template:
          # keep for 14 days
          ttl: "336h"
