apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    DOMAIN: ENC[AES256_GCM,data:2kLKzx67iDtz5gS+i33ZQUhnRUmnaZ7M,iv:u10ax7dvV6DaaC1EcL27De5NfSwRIX9OX359HthCs6g=,tag:KyAwRs5f6WaVwMbZNZFeQQ==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:OVavmmCzaVzWi9WwNMzFA4OL017SqFQBYi+bffIqcIo=,iv:FhIjPRbkZpvDSVcNdrtbYAIuZHYtSYuzZuEiC3BBUFs=,tag:PlraxisnwiKW6pqzYR7nBA==,type:str]
    ADMIN_EMAIL_PASSWORD: ENC[AES256_GCM,data:2eIWRlnit48JfDRz4+9YEgk8YWg=,iv:oTiBu0TdMcw6Y1noQoUEX4f8T6BU6THQPKTwu7r7ssQ=,tag:oKeeQLy9jqlc+10CtaY0rg==,type:str]
    CF_EMAIL: ENC[AES256_GCM,data:qWEpvwHmnQauCEbGUnfvQp9lk4sYuoVWHzRbtfDlLzo=,iv:5ZrnNmKFYbYGQPv84QEKKqk5ORKK9Unxj/rJJ8W/z0o=,tag:3TXzYnyNZbWUN/UoKxdysw==,type:str]
    PASSWORD: ENC[AES256_GCM,data:YeaMfUuCoX88DdrXloh/wlapa+w=,iv:m+wugBLVtqt4BG1K+xLxan9wzN5gYvj4c3jVCl5QClA=,tag:KTvMNYfqGnihH2S+xqO6Xw==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:c9c/xcygg8tndvDx6W5ysHIM0Z7PtCcKkzHRoMhdn+DSFu3WZlqNDEXaedutsuJnvEKiPjmtXHGMeXKXTdLN4Ew5cYCEsM/Ud9oNi55LdPW5adDcCx7VerdcMcXyP49gZNk8MWnK0stq30a8/wD9CHix3N10fdo928ld2QjfdmBaaZqhfWmDKMxze2XEZIDg1QBsMOs5xUU=,iv:HL/Qw444EuJPDJvumOSnEMK/dMFvz93c/KM/cHEu6+k=,tag:Crd+7lOanJ1PHyEy29BLOQ==,type:str]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:AA27Q7ynSwQ=,iv:1AyNohPSsCAFTIlz0oaGrBfiuNr7kGw6KoSetwwj//I=,tag:jKjEg9ixWvpU2jwsNjjo/g==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:4RADcyg27LmPJ4gXSCTz4d8FZp9rfigPAfQVH/E/nvvtluU6SNACzQ==,iv:lz8ZfZ4z/voeyfaU+xqATZsQzIE61vMAKLpX3Z83+lM=,tag:DkM6MBxd4jR/JQAz1vulbw==,type:str]
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:JbDFBAQ6OPXC4H7bdf7BCM/D03Ut42Pt7trgyRaJD3aACe4E,iv:n8SN2Aii09xByJ/tkLLRrkmkK/TBis/mvsT5uIaVzh8=,tag:cBAxd9z5aKrxZwlWPe+ZRw==,type:str]
    PLEX_CLAIM_TOKEN: ENC[AES256_GCM,data:d2pypncwe2Z6OUn+qbu9FAeLh0568XbOOQxwcnKUBvKH8rF/,iv:CYvRQIHA9jMfIGlOVyNhXFokZT0TtEC9po+hQ2aiWms=,tag:5HJTG4aubtmdbqAAVvBgLQ==,type:str]
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:wdGIHsG+g0QqHOnOw285SgTssWvHcmNedpByaGocP5r+419TuBilkgtyo1g=,iv:LmgIh7A3b7NabBIjHiuwBhJMQgvwpXR/Z3GH8Rnecsk=,tag:MnkNbqzEHCt/AM7U6yNYuQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:cD2Ej8YMfk3vHnEifUC02MG4GLnYGlEZEAsjmrTd8ziVlfbHk2Rk0IkWcQ7vJmE/R5yaRKt/XGexLoiPhacDcRpV2ID0C8Ut0BVU+a1ei83H7ZZgTmcYzg==,iv:XDd/6fKxiy22f59PoE962YjPVOADYFhAmIO8T27DHqs=,tag:aOWvGR5Qa4nnuSsTcdnb8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-15T18:04:18Z"
    mac: ENC[AES256_GCM,data:uUNSP5Axw+scz8STMiMawwh4TGBq3W8PEqvDFXYG8XpgpK2mNAsvxNN13l8vrNZn4XMIrA1AU9wHHRgGBssDZFgYvhnXVT4AEWQmNvbJnXudDq51MA1boZzrSI2gj5XE2gX/AAKW9hX5Qo4xT0v+P2tarA2JYHc9EmUPqI8q3+0=,iv:4bYsLN5WDAAusrAFvmuekb2LGSvn6MqoEmL3+rmcIsU=,tag:vzcMxQ5ONdbAC0UXmGKgdA==,type:str]
    pgp:
        - created_at: "2021-10-19T11:47:29Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1WMABwclg+7ARAAphjQdVUJZ5Cki2pJ/wkiNcmcuhCjkDkhrb9c/Y7P2ZzN
            erJ4KPQTkFO5zhHfxicu0zKRSKSzmN3OimnCYIRtgIkk/ynSzX1QMSaz7WbtpuFs
            Q/5W0CujRVddSmGjBFc3F4q38booT+F3aW+Htmy5eD68ZjpxJTtXAu/QwypVMN0K
            gFSuZoQDHGJpFrpv/apED7/dVuSi/JvWjvvs2acEKbr/RvCIpi12g/sp0ckWjPFq
            Q0dIvHQAJNbdcLcmPjBe8ZSEJNTfsz+3Jci+NYZM0qNi6Ok5auUKfZ4dXushfbic
            mUvOgbAfQW+RCDSz+3uAerUNcY3Cdm3Osw2S2AG6a8LmR/HGzUAu9Ol399aqjn30
            +dVQzx8fC1QZMbEqOY30eBmiyB5XR4xItbVTE8jBo2eJDGOe+TEEuSIOFMfdCCFF
            rNAxpTrw6QzSzj72Ld///vBd00AvA1irhuxXndXTGBhsrXsMItocfcn70DdiDbTq
            OqaKTgIE/8ha/+fvEXK+gLycJf/OenNsrgABHqb0pr2gMifqr0ZxMgyEhX+5c39V
            4K9XuOZPgel6xrT2tHXPnIzhAeF4/H3X4RhMQBbuopFauEg5LxkhFCX7I1O1p+0N
            dIU+jrovtD0seRNY/UNTjX53+kzt+cLWY45MHuPx5+cYY1HKnPzdacMJCzcaYurU
            aAEJAhW84ZsTpoL6rSuPISTyQCC07GQjDFRDI4KRuSWyDVBfu4kUiEZ/cPBYEGwm
            ZqnBH/fVcvUe/6lxe7DjS+Z+AxrH4ofdVpeR40968T4PdgapOUfAxD7jPOJ7kL0N
            kHtG2lX4KHAd
            =yxX8
            -----END PGP MESSAGE-----
          fp: E3CF3A557C3A53798EB3964606BAED053E44C047
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
