---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-external
      namespace: kube-system
  values:
    image:
      tag: 0.112.0b1
    hostNetwork: true
    persistence:
      storageClass: nfs-kube
    monitoring:
      enabled: true
      serviceMonitor:
        enabled: false
    vscode:
      enabled: true
      image:
        repository: linuxserver/code-server
        tag: version-v3.5.0
      extraEnv:
        TZ: America/Chicago
      args: ""
      service:
        port: 8443
  valuesFrom:
  - kind: Secret
    name: "home-assistant-helm-values"
