apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-helm-values
  namespace: default
spec:
  encryptedData:
    values.yaml: AgCLV0+lr8UKYxr2GeQfnT7FN6qUJmdNY+83TlFaVgIKACM5rsl2XXcjWkYJ/aUB7srlHbTRkFUvScZbbX9ZfcZohz7ontjf8J3RpRlsDxHDO+TfxeVrCbUVri0bHc4oSME2VXQXAL4IoXkpisOm2NEAMc+ElA9VnS5LkJvmIKG218iY9pPPQF356pOiHVU9X7JZkgT0+TXCzVAcfTuR+sYVZJ1RHl5NBFJ+QTYCItfrqT34BYC159SRx/CkVhPOuuNAeq8+dKqOM5aWRjgdcCgWccuK25/lKI00561excjZUTN9bKIpIjOkdA1OxufJfkJVpksz8b/diIQOc94KoVtCYQ+Z/xLvIbhj62z/oC6g5kvyHxlRO79XqeBw2HcM8qhGvovp9nPwm9l4UNpfyrbBI4Ey+QfmvmT93p4YJDkybsl/zrGWeAwOAVQTsq7SNZ/WniSe6vPz9xvJRmf6v95ZN6myeionjXbEn7XOoC1sEGp0OOoAeXCmRwULSQ10BzAV4hLQ8qZUhJLC3vKbEOKsXJ+9LSSIkWID+ur16a8mTFhRCqDVp/6NYw6A5iugJIfGGgZtG+UDg8j0/vp1KKexWynvUO1QVXaHF9F/AlX443zGCv8wHCRbI/8TJcHSrWdisjKzAE9CgwJNO8wF5UJOK60rMH+B0bEVPXNMhvo3/DjtundfZsJwBU4/x2qTUfrOt44XYEDyI7NWUWzXhpTpHsoxL0EUAWPbW6sRY53mtU7w/ErNZd21HzWdi9BIrfZxW4yZLwshVnTW5JKMsHrrXlwczc3e2k1Iw1r+GcYF6B/0uVeX0kGdWQLTl0+FM9rAZBhTn8Rks8JPm0o2pE43DLxxv6O1D/8b7ShJICips7eC8V1VNR6l+eTQDcQan6d37qjNU7Ps3c9AgwnVnb3BGf2pDm3/ztDlsFx7WUWPinfG1f7pS9ONE3MTeWAc8XmVXvsJe54Wf3fjBoZQUiBwdb4VmYAjJoqmZYyTM3iqGMCIWmF0t5+NgpQ5yrm1yfhq3HNrb1Aq7AdSQfUzPnYkIHiC+2HCsEr3xyUDUVo5AOPbb881H6SjiwvLWfw7OV2jVnVY2kxMJK8as5eMvLXwpO80d51VL1HveZvBMcvMis3T3MGoZC7xPKlICpKu/UNlOGobC/c=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-helm-values
      namespace: default

