ansible_host: ENC[AES256_GCM,data:gNzLZGkO69CUGFKXMg==,iv:bxIX2mZz31cSqKHmi3pxBZx9qrGSsl1nC7se41cVHm0=,tag:rcEBOFmE+UYFiiaa1qLgIg==,type:str]
ansible_user: ENC[AES256_GCM,data:VVvo,iv:4Ss5CUYDqQuPBP+FvTnTu9tEMYj1VQ2x/uAQmOTQmSk=,tag:QZ2gAhUvD3ORr05fD2Xz5w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:vNBnhcEImPDx7/9sVA==,iv:DqyaZCTpZRwnDEkyO8b66HzUqKF9e6hKzX1SefxnDbQ=,tag:TrjxDlzlyGcDx8BzxrmaRg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-06T03:13:48Z"
    mac: ENC[AES256_GCM,data:khhB30xDpWaKcn3mN8XcyiGGSXwAg/hyM5ha7qXjVGBdgQqCGrI7TDOfEl/sr32aDIBrVIeSC0+fLF8XatEg51xgx97IMCUVP1JIBy2XZIEQiSyEfGoS6P3w+Kjd9DNlMNDccYZlGKPmBnPAiva30OIboVBCv82jJgo6unJVS/Q=,iv:Z87WmHS/dLuBZ6piklVyi9fR81chLTj6dj290ejbKwc=,tag:WiolPuGIdDUMy8dduaK12g==,type:str]
    pgp:
        - created_at: "2022-11-06T13:27:53Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1WMABwclg+7AQ/+NyDeNE5pntItZ6LpwOX+i7Bwbka9MoMCZJSJ6yDebYp1
            2uqD3GbKvQWQGVzcXBxEsyjhRny1hqy2tz9QqcxCu1zoenmI4zCDp1xqiyMNdEqW
            JLHhmykwG+x9FEg4HpTt+K5pgm/J+5e5/Nd9+wKmY+8A15UlhQ/YsBy9WBjLxLql
            4Ss5DdmgcUi7W+3Ow0ixfk3MDAsaluM5SMF5s6JRwL/5kkgucC5B+/LjbfyWXDFj
            6MJ1hMEgWjLoCGhu28x5Ml2ykn+LJ9I3yeEJD09ASki2PqSYvDnIfVrAUjZidy4n
            Q07+Zmr4sEc9CqcS9oZgliIrzgjRLMlmNyFnXtk+SC6U940GPadgk8fmW47zR7SE
            X2BbYYfTJn1IPp7a5+KaB2BSOlrk+VBu7V3o0jIMYfFC2B4aG+vOUbBUr8hAcyrX
            Lz/ZcnS23CzzmF5ak6g7be6/4k5ukPNh6YuqyXFEeXXwchcFM84PorAsQqiBDYBi
            v+jVRrTl9UZ4B0vWnvxJ2nmpcjbQwkReyuh6mzq/VP4u4Dek63SX5lgOGqmU8CWx
            Qky2yJVXH39unAc7q0ZLdgSTuEgKdZ0ZC4xCCy5biiqdQAb7r4HDmalAZMYH51VF
            9sVD8NLrwWT9H5HUQr47qpCT7LcMdmPzsYu99kh981+15YDoAMs/bhWfnImxmePU
            aAEJAhAV39nFrD91rQHABw+T5Y3M9y3TFmd2pU5XysnhblXguyLl9TKnbu65nQ/S
            Eg81Nrj2Mw+Iwr4tca3tgwyVcn0q6qFQsbbusZ2btRlwAvo5y3QgJoQ2c0R9twqg
            Hahe65x4iQMv
            =jKwp
            -----END PGP MESSAGE-----
          fp: E3CF3A557C3A53798EB3964606BAED053E44C047
    unencrypted_regex: ^(kind)$
    version: 3.7.3
