---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-external
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  values:
    controller:
      ingressClass: external
      service:
        loadBalancerIP: 192.168.1.11
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"