---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    env:
      PLEX_CLAIM: "${PLEX_CLAIM_TOKEN}"
      TZ: "${TIMEZONE}"
    image:
      repository: ghcr.io/k8s-at-home/plex
      tag: v1.28.0.5999-97678ded3
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          nginx.ingress.kubernetes.io/app-root: "/web"
          external-dns.alpha.kubernetes.io/target: "ipv4.${DOMAIN}"
          external-dns/is-public: 'true'
          hajimari.io/enable: 'true'
          hajimari.io/icon: plex
          hajimari.io/group: External
        hosts:
          - host: "plex.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "plex.${DOMAIN}"
            secretName: plex-tls
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      movies:
        enabled: true
        existingClaim: movies
        mountPath: /media/movies
      tv-shows:
        enabled: true
        existingClaim: tv-shows
        mountPath: /media/tv-shows
    service:
      main:
        annotations:
          metallb.universe.tf/address-pool: default
          nginx.ingress.kubernetes.io/server-snippet: |
            proxy_set_header Accept-Encoding "";
            sub_filter
            '</head>'
            '<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/plex/${TP_THEME}.css">
            </head>';
            sub_filter_once on;
        loadBalancerIP: "${PLEX_LB}"
        ports:
          http:
            port: 32400
        primary: true
        type: LoadBalancer
