---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: heimdall
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: heimdall
      version: 6.4.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    image:
      repository: linuxserver/heimdall
      tag: version-2.2.2
    env:
      TZ: America/Chicago
    persistence:
      config:
        enabled: true
        existingClaim: heimdall
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
      tls:
        - hosts:
            - "heimdall.internal.${DOMAIN}"
      hosts:
        - host: "heimdall.internal.${DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
