---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grocy
  namespace: grocy
spec:
  chart:
    spec:
      chart: grocy
      version: 2.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    timezone: America/Chicago
    persistence:
      config:
        storageClass: nfs-kube
  valuesFrom:
  - kind: Secret
    name: "grocy-helm-values"
