---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-client-provisioner
      version: 1.0.2
      sourceRef:
        kind: HelmRepository
        name: ckotzbauer
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner-arm
      tag: v3.1.0-k8s1.11
    nfs:
      server: 192.168.1.105
      path: /export/k3s_nfs
    storageClass:
      name: nfs-kube
      defaultClass: true