---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: "192.168.1.10-192.168.1.20"
  INTERNAL_INGRESS_NGINX_LB: "192.168.1.10"
  EXTERNAL_INGRESS_NGINX_LB: "192.168.1.11"
