apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    CF_API_KEY: ENC[AES256_GCM,data:I2PXGzd1R9xQYuffur3FpKMrZSGkBmais22xXdMURZnxtAJdCe7acuBuherXcLHR/2+UsQ==,iv:ILG0Py97AJ+rtOnGf7FMF9Aj452yaBNrMUu5R9cvk/I=,tag:ro5OJDp8JaUXl/fd/GPKCA==,type:str]
    DOMAIN: ENC[AES256_GCM,data:fYn51SjubWh9mJZ5Up69t7g+YRLmkNZE,iv:FYjICdoW8OqpBUPR91y5XEK/NdbyIRI1W1LpdWqMUyc=,tag:oXZkOIm4TcenQePh8J2R/A==,type:str]
    EMAIL: ENC[AES256_GCM,data:cIMmQOBBXoCDWZMTRDC2/I7HjhYYojZjdq1K+hWgJ8w=,iv:ibrZZfNMx3hvRePPzn6D1kGqW2p3wMlsJrRO2sdvWbc=,tag:Cpam59sOWzRY1NmqxenHrA==,type:str]
    GOOGLE_APP_PASSWORD: ENC[AES256_GCM,data:p4an2OC2h6KLTJ9Lgr7bAWcsIfE6zxRv,iv:BlucIKsE1L4R7QlopivwT/DFshyOkTm51sHK2QlSQ3k=,tag:jb9C4gvFsz9q1e21E6YfLg==,type:str]
    PASSWORD: ENC[AES256_GCM,data:/zO2g8b2lsKF0KMN0UU1qrls/bw=,iv:P+83DZg77UNmqO+oow862nniDY2+PMWskx5lK+MzTuo=,tag:F8bdm4hpHAh4W7sj+JR5dQ==,type:str]
    WEBHOOK_URL: ENC[AES256_GCM,data:fs2KnJFVg9jBoEFe66VFy7fZ5EfW1vb+zk4mesTk1AKcs1RBWYUBFoOKXYuVdZxM2eEqBm/3oGCuEPmMdkc3ES+1kbaZMkvE60i6qWDJekma9IOdY88TtZXqF8669ZYJQv/7tbkphpGADn4in055ET8Lk+4aOCRfuqNdQwOTSHpFgphTItZ/AsUCjHXi+b7LWArtxQca1x8=,iv:AkX452b2jUEW17RmybJRWuuynNbd2pkbQ5z14+I7H44=,tag:CvFJFZ3RAsfqG1mTYbH9/A==,type:str]
    YUBICO_CLIENT_ID: ENC[AES256_GCM,data:xED9ngeQRlY=,iv:lsigdGYXIH2YE+zbCwxYMR+EnuaMYWjNmwycJ/pE7fU=,tag:jin7A6c6rxCvHpJr7i8yFQ==,type:str]
    YUBICO_SECRET_KEY: ENC[AES256_GCM,data:RXdcGQeSlLgBCnPZ+5cNyy08DVwvsS7MjGCDST0+91Q6PRcRTjR4bw==,iv:N/G0wFW64X74nVtwrtY26fRgK4Vi9hdjy/lghqfU2ZM=,tag:UC0rXL03x2+5nmF76q++rg==,type:str]
    VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:O/93NO9NstN3DfKp1TZCnMl3Gik6v14NukAMJGXiba2HKoKgvLVjGqnl8tkaM7FXN3i9GqP2Sd+aTH7noVUea7Anr4ZfVHgTIPlOws6zXxkFZ/sTEoAE4A==,iv:MII/TZ3oPlPjjRDeyfqIJvsiL1TlPwHWmYMJrqsfa6k=,tag:KZ2lclBAVnRzh/UWca88fg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-07-20T21:22:03Z"
    mac: ENC[AES256_GCM,data:i5PwV8esQGJZ5sgQ39+BjJdFIRmR9mA3cyvlO600P8yHj/coiSvs2EufuygPdirhPJj71jHpqp54JT283E3BHnkjt7zXexm3v6MXXEmxUTFMNLAfS8Vi+hW6qm86BS7cNQp7QgP0v7t7nOWnIgEXGmMkH6PSe5vyW+WF8wSGfr0=,iv:vlJqbA9ZgXio1Pe9vWf7tcEf/JVovztw3SQiwoYx4kU=,tag:pZCdMoyga5/liOSzvIagYw==,type:str]
    pgp:
        - created_at: "2021-05-15T19:48:24Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA8ZcbtKl/witAQ//XYGYm+LkO6bIqwlIvJu+NSKRu7Sw2QTeRUT/Kwb07ctn
            ZzxbEiFDIca4hqojbuhLDOWJzW7XTtRcXvbl0cGB75sZQvxYQFyFM5FvV3VNRzcg
            9GYEbkB850EFBEz9JGbdbJBoFEm1iDeVVsC40+qqJzhhdTw39ph0UBNIpYtOGm6N
            ei8hYBmOXm6wDPX2M5NjPyliQPF2gy2ISnBEOIvreKU0cx9/hHY4lsd6fDsWDKPo
            Dtz8YgWTqsQuxmTF8ygcu0FeVhO/xYyJyohB3DTTSoWHgdRlc23k3Zr1RXw/pV7t
            DsNlO3aV7hb/vs7bu1zk5LYuYJLEGOM1oai5XDBjrqmyg1RgRo1qkqTYNVtSURM/
            j6CerVfskthBmYwNmZa09QPq1LVSwl1NgFDFcmxGbyfeeeR+Yj24YGS7AE6vROk7
            opYjOSk8LFiHfNcnlV8xmrkdHXyuJidEombFd5kQK/ZDwh5VvTIHSDe6wYb0bdsy
            6jJfGwsxgDX/miIA63YtcP7vgkSSFCSFep5wCvRw+khkDxxk4dsH6h3BypBHwA3W
            +oAqVodab1NSMnN9zbUjDHw/EwD0Lj75QQ4cjVbbOlfNh8eES+NPAu2CfRU3VL+F
            9P8m9X0UlPbAFxqu+RoD305aRt2QNyD5WOgKQg2+girs7rzcD5ofP7spQf7k4UfS
            XgEnfEFknKAumxYmZQAmNIFyT7tYKuCJatYqhZ/PR/bpE//iosSU3S1iN05Y7rqO
            nYxibs0aeuO5hnJuhEko0Vdf9DqAUulDiFGb2QgbbxkVsFziuvZ6MND6f9EtCDs=
            =BfuO
            -----END PGP MESSAGE-----
          fp: CE7A33EE11115397283AA4737BB0A5513DCF018F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
