---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx-internal
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 3.15.2
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    controller:
      ingressClass: external
      extraEnvs:
      - name: TZ
        value: America//Chicago
      service:
        externalIPs:
        - 192.168.1.10
        externalTrafficPolicy: Local
      # config:
        # ssl-protocols: "TLSv1.3 TLSv1.2"
        # Setting use-proxy-protocol to true will break the proxy
        # use-proxy-protocol: "false"
        # proxy-body-size: "0"
        # use-forwarded-headers: "true"
      metrics:
        enabled: true
        serviceMonitor:
          enabled: false
        prometheusRule:
          enabled: false
      # extraArgs:
        # default-ssl-certificate: "cert-manager/acme-crt-secret"
