---
warn_list:
  - unnamed-task
mock_modules:
  - community.general.timezone
  - community.general.modprobe
  - ansible.posix.authorized_key
  - ansible.posix.sysctl
  - ansible.posix.selinux
  - ansible.posix.mount
mock_roles:
  - xanmanning.k3s
  - geerlingguy.nfs
exclude_paths:
  - cluster/
  - .taskfiles/
  - .vscode/
  - .github/
  - cluster/
  - provision/terraform/
  - Taskfile.yaml
  - .sops.yaml
  - provision/ansible/inventory/host_vars/
