apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /export/Node-Red
    server: 192.168.1.105
  storageClassName: node-red
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: node-red
  volumeMode: Filesystem
