---
- hosts: all
  vars_prompt:
    - name: timezone
      prompt: What timezone do you want to use?
      private: false
      default: America/Chicago
  roles:
    - k3s-common
- hosts:
    - master
    - worker
  roles:
    - xanmanning.k3s
    - k3s
- hosts:
    - storage
  roles:
    - openmediavault
