apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grocy-helm-values
  namespace: grocy
spec:
  encryptedData:
    values.yaml: AgDH5+HJp22guUSJuAvejRos4AftAbDskq8kLx5YrZ/dnI+QTyqaQeFNqwyLTIPNZKM7HUbgvJqz1Q2+mwCL+uXsfFKHHHIHr5Y2YmcGocYjJQDN6L8WudGtcQ0GjihNKulkXH8yK8y9c+1XwSnQ+6r3ij6QZLzOeghu+R1zfrignQeWXP1Y55aX07GSm1isGDXvRI+LtMEskn1ZjqJj+Nsscg+nZS1V/ZDrgDMplv2akQHrwABcPrZ24+1hmeAum6mUaXjJlKCWv6tdNtWNrRSEcU0tsYchtt80/lbI0B84AwWgaog4gD5Yqxk0QVX42uTEzUvoWM7OBxYiJj8cDR89oqw93/uOzwXwx9g9MlQmLT1EMtXW+JOxtm2Q63+WqxKvWkCPpj6sV+72GjST9S4i1Dm16dI1enqJc1mioPmlxMNh3WBjPfpSN50AWaKRE2EN4cmdzYorqIzByc672wxwk6aB1FF1BnGdq82C5IZLYhMDaQrtTpwV2McFRDcIQaHdG0zKi1/pvIJzYviWW7ZUG3zSh1N5F4smRAgy2GZIInxOSayWw7eBL1VEldhMQr7IrEWdh340fXcZDUzC8Pdx1Qqxz/xliYejeK0ckFrwky5rkVKaFOVX+EfYsrvp44jC2LYU5QZPzB91MlGc8axTsubmf0j7XsrobQxZBA2C4X0Kqi9pevAbDuPDv4phHU9Dyo17VGI5JdrDS8uJDxAXCTf0+r7uFG0yr7DTrZzWDksZMuH3CKONHU+cQJalG3b1U7JjzI3iRHV/oUcix4h7xtA8v0s1MjQMkelnLd16xHkTOHRkUlu4geuD886FeWziNLelShyL6wLoTnj2Az+7Z9tE3p0P8Fu73KS0bqpOX+L4qsYY+GnS+FjPUbzc2jniuzBphrTM0vA9bHqc2QpeyGFgoMuAwzvXjmLRWjpgCcjp5cnkdr8=
  template:
    metadata:
      creationTimestamp: null
      name: grocy-helm-values
      namespace: grocy
