---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      chart: vaultwarden
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: vaultwarden/server
      tag: 1.26.0
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "safe-square"
          hajimari.io/group: External
        hosts:
          - host: "vault.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
        tls:
          - hosts:
              - "vault.${DOMAIN}"
            secretName: vault-tls
    env:
      DATA_FOLDER: "config"
      DOMAIN: "https://vault.${DOMAIN}"
      YUBICO_CLIENT_ID: "${YUBICO_CLIENT_ID}"
      YUBICO_SECRET_KEY: "${YUBICO_SECRET_KEY}"
      SMTP_HOST: mail.privateemail.com
      SMTP_FROM: "no-reply@${DOMAIN}"
      SMTP_FROM_NAME: Vaultwarden
      SMTP_PORT: 465
      SMTP_USERNAME: "${ADMIN_EMAIL}"
      SMTP_PASSWORD: "${ADMIN_EMAIL_PASSWORD}"
      SMTP_SSL: "true"
      SMTP_EXPLICIT_TLS: "true"
      ADMIN_TOKEN: "${VAULTWARDEN_ADMIN_TOKEN}"
      SIGNUPS_ALLOWED: "false"
      DATABASE_URL: mysql://root:${MARIADB_ROOT_PASSWORD}@mariadb.storage.svc.cluster.local:3306/vaultwarden
