---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts/
      chart: prometheus-community
      version: 12.10.6
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-internal
      namespace: kube-system
  values:
    alertmanager:
      enabled: true
      alertmanagerSpec:
        image:
          repository: quay.io/prometheus/alertmanager
          tag: v0.21.0
        logFormat: json
        logLevel: info
    grafana:
      enabled: true
      image:
        repository: grafana/grafana
        tag: 7.3.5
      additionalDataSources: []
    prometheusOperator:
      image:
        repository: quay.io/prometheus-operator/prometheus-operator
        tag: v0.44.0
      configmapReloadImage:
        repository: docker.io/jimmidyson/configmap-reload
        tag: v0.4.0
      prometheusConfigReloaderImage:
        repository: quay.io/prometheus-operator/prometheus-config-reloader
        tag: v0.44.0
    prometheus:
      enabled: true
      prometheusSpec:
        image:
          repository: quay.io/prometheus/prometheus
          tag: v2.22.1
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    kubeProxy:
      enabled: false
    kubeEtcd:
      enabled: false
  valuesFrom:
    - kind: Secret
      name: "kube-prometheus-stack-helm-values"
