---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgAmHaG0njfgAATSXD3HdYTTfhMGH/EcSpKIffSRjRMw+bZ6mHOLoI8Fww0XQtZapWlnTbdNabwf/Hn2l/HDgm4YOrBQb1htNpHcxhjKcRNrssP2fwrZZOGg9coMr4spvAGoQJ+rJiB0tZ/YHmLXr/1cuKjYmQsU2kYB3fUov4B9rYzW/ibGeLpycYU96BTwszabU5/X3Rc2lbtv/0ccKmOUJOeyoJwx5eq9oqQ3RHnORmq18TX1BdAO1GoFxzjxjSOTOPUc4ru4jWkOhcf6xqYa9comnJ4xu18z1QrUYlbOFNXoT8pZpjqIo8tnzxCcm6/T5I06s9y1yzmjfnF4uZiCPHnxcE+BP6c8W9xzAq/v9r465TFbwoMV5SEooN9EX9x23JnrsNmlkEz1WcYMe4BJg614+Sd1MYqJchxbjUvPT5C63udDlBYDTBTxROUjawUZjG6sUuxu91a3m46/aqtHOm/+snZ10yzwYACH4n7pTvIBl+ushUPHF13+xWrsQW/tDPbJcYSuO8L2TjYFP8My3n0Mq/rO22CDw5f95e1CBKVay0TU3gcE0Pyu2Mc6xxnaByfKin2TV+QcMEQ1AilUelSHeBpcUbxlY+sYN3+dUqm0cb+QNXEmokcKQaJqRSyyKlxzEBln2zKGvFRTNp5xSGeEvr4PXyq/VQuZZsT/IBLdInnbxqGeDZNe5BjWwbQT8IyYakNKtXF79uubLYmDuA7Xgurttv++K8UoTFizTaC9xcCeA4pKGNIJ8CKmNjCdugaOySToJCP4K0vqUJAaGyq5Jzi+H8EPe7cpB2f+TPQ=
  template:
    metadata:
      name: slack-url
      namespace: flux-system
