---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-issuers
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: networking
    - name: cert-manager-issuers
      namespace: networking
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: acme-crt
          namespace: cert-manager
        spec:
          secretName: acme-crt-secret
          issuerRef:
            name: letsencrypt-production
            kind: ClusterIssuer
          dnsNames:
            - "${DOMAIN}"
            - "*.${DOMAIN}"
