---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ombi
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: ombi
      version: 11.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: ghcr.io/linuxserver/ombi
      tag: version-v4.0.1430
    env:
      TZ: "${TIMEZONE}"
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${DOMAIN}"
          external-dns/is-public: 'true'
          hajimari.io/enable: 'true'
          hajimari.io/icon: message-video
          hajimari.io/group: External
        hosts:
          - host: "ombi.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "ombi.${DOMAIN}"
            secretName: ombi-tls
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
