---
apiVersion: helm.toolkit.fluxcd.io/v1beta2
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    image:
      repository: linuxserver/jackett
      tag: development-version-v0.18.532
    env:
      TZ: America/Chicago
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://homer.${DOMAIN}"
        ingressClassName: internal
        hosts:
          - host: "jackett.internal.mysmarthome.space"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jackett.internal.mysmarthome.space"
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      torrentblackhole:
        enabled: false
        mountPath: /downloads
