---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: jackett
      version: 11.3.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
  values:
    image:
      repository: linuxserver/jackett
      tag: development-version-v0.18.532
    env:
      TZ: "${TIMEZONE}"
    ingress:
      main:
        enabled: true
        hosts:
          - host: "jackett.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "jackett.${DOMAIN}"
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      torrentblackhole:
        enabled: false
        mountPath: /downloads
