---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reloader
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: reloader
      version: v0.0.124
      sourceRef:
        kind: HelmRepository
        name: stakater
        namespace: flux-system
      interval: 10m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: reloader
