---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  chart:
    spec:
      chart: node-red
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    enableProjects: true
    timezone: America/Chicago
    persistence:
      enabled: true
      storageClass: nfs-kube
  valuesFrom:
  - kind: Secret
    name: "node-red-helm-values"

