---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: node-red
  namespace: node-red
spec:
  releaseName: node-red
  helmVersion: v3
  chart:
    repository: https://k8s-at-home.com/charts/
    name: node-red
    version: 3.1.0
  values:
    enableProjects: true
    timezone: America/Chicago
    persistence:
      enabled: true
      storageClass: nfs-kube
  valueFileSecrets:
  - name: "node-red-helm-values"

