---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: linuxserver/calibre-web
      tag: version-0.6.9
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      books:
        enabled: true
        existingClaim: books
        mountPath: /books
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        tls:
          - hosts:
              - "calibre.${DOMAIN}"
        hosts:
          - host: "calibre.${DOMAIN}"
            paths:
              - path: /
            pathType: Prefix
