apiVersion: stash.appscode.com/v1beta1
kind: BackupBatch
metadata:
  name: deploy-backup-batch
  namespace: demo
spec:
  repository:
    name: b2-repo
  schedule: "0 6 * * *"
  executionOrder: Parallel
  members:
  - target:
      alias: bitwarden
      ref:
        apiVersion: apps/v1
        kind: StatefulSet
        name: bitwardenrs
      volumeMounts:
      - name: bitwardenrs
        mountPath: /data
      paths:
      - /data
  - target:
      alias: freshrss
      ref:
        apiVersion: apps/v1
        kind: Deployment
        name: freshrss
      volumeMounts:
      - name: config
        mountPath: /config
      paths:
      - /config
  - target:
      alias: home-assistant
      ref:
        apiVersion: apps/v1
        kind: Deployment
        name: home-assistant
      volumeMounts:
      - name: config
        mountPath: /config
      paths:
      - /config
  - target:
      alias: node-red
      ref:
        apiVersion: apps/v1
        kind: Deployment
        name: node-red
      volumeMounts:
      - name: data
        mountPath: /data
      paths:
      - /data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
