apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: bitwarden-backup
  namespace: home
spec:
  driver: Restic
  repository:
    name: b2-repo
  schedule: "0 6 * * 6" # backup everyday at 0600
  paused: true
  backupHistoryLimit: 3
  target:
    alias: bitwarden
    ref:
      apiVersion: apps/v1
      kind: StatefulSet
      name: bitwardenrs
    volumeMounts:
    - name: bitwardenrs
      mountPath: /data
    paths:
    - /data
  retentionPolicy:
    name: 'keep-last-5'
    keepLast: 5
    prune: true
