apiVersion: stash.appscode.com/v1alpha1
kind: Repository
metadata:
  name: b2-repo
  namespace: home
spec:
  backend:
    b2:
      bucket: raspi-k3s-backup
      prefix: /backup/home
    storageSecretName: b2-secret
