---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: booksonic-air
  namespace: media
spec:
  interval: 10m
  chart:
    spec:
      chart: booksonic-air
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 10m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: ghcr.io/linuxserver/booksonic-air
      tag: v2201.1.0-ls73
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      audiobooks:
        enabled: true
        existingClaim: audiobooks
        mountPath: /audiobooks
      podcasts:
        enabled: true
        existingClaim: podcasts
        mountPath: /podcasts
    podAnnotations:
      backup.velero.io/backup-volumes: config
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          external-dns.alpha.kubernetes.io/target: "ipv4.${DOMAIN}"
          external-dns/is-public: 'true'
          hajimari.io/enable: 'true'
          hajimari.io/icon: headphones
          hajimari.io/group: External
        hosts:
          - host: "audiobooks.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "audiobooks.${DOMAIN}"
            secretName: booksonic-tls
