---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: booksonic-air
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: booksonic-air
      version: 6.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
  values:
    image:
      repository: linuxserver/booksonic-air
      tag: v2009.1.0-ls2
    env:
      TZ: "${TIMEZONE}"
    persistence:
      config:
        enabled: true
        storageClass: nfs-kube
      audiobooks:
        enabled: true
        existingClaim: audiobooks
        mountPath: /audiobooks
      podcasts:
        enabled: true
        existingClaim: podcasts
        mountPath: /podcasts
    ingress:
      main:
        enabled: true
        ingressClassName: external
        tls:
          - hosts:
              - "booksonic.${DOMAIN}"
        hosts:
          - host: "booksonic.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
