apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openfaas-helm-values
  namespace: openfaas
spec:
  encryptedData:
    values.yaml: AgAkdZxSs8BoSkhURMhsl2uaVedhFQYzUW/ixfkC4iyrP7goT+8Pfzk4c24CR+1fi9QzuFUikMRsuV3u7AYOCJsnOtLbRfIkgRscCgnsb+42IDkCnjO+TuH6l9IHsnRH9jv949e3TFhQFsKdmRGMl95P8/esqxPlawr/wKCEpuzgfNimcp2LKP9AA+MvGwQrmXHlTyFgbaB8sZou1KllUpwCG/AVzn+SpDjp5z17KTF1Jmxg4rNHmLr2IYUNFj1uyLEfbKwOqm12W/dSlTBkVRAczAQhiXfN7au04Le0duGC7CTLB34zTB2ZmySSPrY/C4p9lFN3sEB+nq6uu7JvAvuplpnRbEmWVi1QZoJ+AFh0TBpB+L6FM7k9aV4yKy4LYP0pl2kdI9mUHZBRZW5kV9tnnvkUhFV3cA4JhTf1anRadJNWkFkG9hEsurDsqFP7iVPkwdmaACYYc3e2V/9ObpA55CMEB/znVAXoB1mMR9F3IOTEpBW6QealBt6RzzMuvJgexu0ibeISVzfYkr/aHr1bYGSunsZ3Psy09LWiatDdpWaayQT6vGXw+bTd/edvB+qfe0uyWeaO0sDn3fG/hHpFNkxZFtOclWEbY7sZmx8JAMVZWR71dHRQlLL0JWOG6AmElTQo6NI9xfRuPPVYeuDU4kJI2Jf3mIbMLvVbYBIGF5cWDSsK5Y99kvcMEcxN6hG8FdaR309/hatVFVdsXeydvc9rVlOCA8c+X5wpSmUW8JGcSn9S2LATJsmV18BlMFfT8ZVc4zwNkFk61VGkL7Yfp5oSAmdg3moTkXRwVLHrncV43+NiAryyHzpUowWb0xe56YtBAOP4nWRRIpq3tc1wRd4kFN8xqbX6VhHbyEuZWUG9QgO5JQFCECxRaOo4UpzXtVH2Vpy+ZvvExjEft2/Vxrke4SaUSSTf+JJrsQpqGzVWlIYxojjOwuOR6PY4a3Qux+Xl8oQSnJ1h36IdBkIN9HY4P6b4KwrEJfmTjnWw2oW3hAChMDVQjoWGoUN1UHQS6JZYPd6/Jqbj+HgO1kDtjF0=
  template:
    metadata:
      creationTimestamp: null
      name: openfaas-helm-values
      namespace: openfaas
