---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: openfaas
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://openfaas.github.io/faas-netes/
      chart: openfaas
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: faas-netes
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: sealed-secrets
      namespace: kube-system
    - name: ingress-nginx-external
      namespace: kube-system
  values:
    basic_auth: true
    generateBasicAuth: true
    serviceType: ClusterIP
    nodeSelector:
      beta.kubernetes.io/arch: arm
    gateway:
      image: openfaas/gateway:0.18.18-armhf
      directFunctions: true
    oauth2Plugin:
      enabled: false
    faasnetes:
      image: openfaas/faas-netes:0.12.3-armhf
    operator:
      image: openfaas/faas-netes:0.12.3-armhf
      create: true
    queueWorker:
      image: openfaas/queue-worker:0.11.2-armhf
    prometheus:
      create: false
    alertmanager:
      create: false
    faasIdler:
      image: openfaas/faas-idler:0.3.1-armhf
    basicAuthPlugin:
      image: openfaas/basic-auth-plugin:0.18.11-armhf
      replicas: 1
    ingressOperator:
      create: true
    nats:
      metrics:
        enabled: false
  valuesFrom:
    - kind: Secret
      name: "openfaas-values"
