---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wikijs
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: wikijs
      version: 4.4.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    image:
      repository: linuxserver/wikijs
      pullPolicy: IfNotPresent
      tag: version-2.5.191
    persistence:
      data:
        enabled: true
        storageClass: nfs-kube
    env:
      TZ: America/Chicago
      DB_TYPE: postgres
      DB_PORT: "${POSTGRESQL_PORT}"
      DB_USER: wikijs
      DB_PASS: "${PASSWORD}"
      DB_NAME: wikijs
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "external"
      tls:
        - hosts:
            - "wiki.${DOMAIN}"
      hosts:
        - host: "wiki.${DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
