---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wikijs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    path: /export/WikiJS
    server: 192.168.1.105
  storageClassName: wikijs
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: wikijs
  volumeMode: Filesystem
