---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: uptime-kuma
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
    - name: cert-manager
      namespace: networking
    - name: ingress-nginx
      namespace: networking
  values:
    image:
      repository: louislam/uptime-kuma
      tag: 1.18.5
    env:
      TZ: "${TIMEZONE}"
    persistence:
      data:
        enabled: true
        storageClass: nfs-kube
        accessMode: ReadWriteOnce
        size: 1Gi
    podAnnotations:
      backup.velero.io/backup-volumes: data
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/enable: "true"
          hajimari.io/icon: "wan"
          hajimari.io/group: Internal
        hosts:
          - host: "status.${DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "status.${DOMAIN}"
            secretName: status-tls
