---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes
      chart: pihole
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: mojo2600-pihole
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    replicaCount: 1
    strategyType: RollingUpdate
    # -- The maximum number of Pods that can be created over the desired number of `ReplicaSet` during updating.
    maxSurge: 1
    # -- The maximum number of Pods that can be unavailable during updating
    maxUnavailable: 1
    image:
      repository: "pihole/pihole"
      tag: v5.8.1
    serviceDns:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.12
      annotations:
       metallb.universe.tf/address-pool: default
        metallb.universe.tf/allow-shared-ip: pihole-svc
    persistentVolumeClaim:
      enabled: true
      storageClass: nfs-kube
    DNS1: "1.1.1.1"
    DNS2: "1.0.0.1"
    adlists:
      - https://raw.githubusercontent.com/kboghdady/youTube_ads_4_pi-hole/master/youtubelist.txt
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "internal"
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-origin: "https://homer.${DOMAIN}"
      hosts:
        - "pihole.internal.${DOMAIN}"
      tls:
        - hosts:
            - "pihole.internal.${DOMAIN}"
    adminPassword: "${PASSWORD}"
    dnsmasq:
      customDnsEntries:
        - "address=/pihole.internal.${DOMAIN}/192.168.1.10"
        - "address=/red.internal.${DOMAIN}/192.168.1.10"
        - "address=/jackett.internal.${DOMAIN}/192.168.1.10"
        - "address=/radarr.internal.${DOMAIN}/192.168.1.10"
        - "address=/readarr.internal.${DOMAIN}/192.168.1.10"
        - "address=/sonarr.internal.${DOMAIN}/192.168.1.10"
