---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: "${NFS_BASE_PATH}/Apps/adguard"
    server: "${NFS_SERVER_IP}"
  storageClassName: adguard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: adguard
  volumeMode: Filesystem
