apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
data:
    token: ENC[AES256_GCM,data:l0/asQioQkXTm/UKnyDX4GwCHl3iPdWGYolejNh2UWpu56110qAYSE6fy+073hhvjhoey8JYQj8=,iv:ki4DOpP0IDylF+Ini6XXGGjsTKQ2+jIcHs+UVlpb7PU=,tag:AK4uc4h3j162pkEmUesFtA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-07T04:23:27Z"
    mac: ENC[AES256_GCM,data:3Ig+axQqT2aoXtM+JIt/bVG8bHENHePLS9q4s7al8/8pqr+Z7HtRQM1ziGF5ympKgh5uQiWAQ0GGEf92xV5qqAxrTL9Nqs8Ma5IXmlZwog+nr+RA7dVUXRkZq6QRYWYBmwC4ugCeptOm44m3CHasXq1yz2fQqSEKa8zhJroCiXA=,iv:OZL0Osraj6gS9qHhh4m9163iRWDmnc2oU8vEsHVgy84=,tag:y7mDHZm+oxjDTs0XoEDU+A==,type:str]
    pgp:
        - created_at: "2021-11-17T12:19:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1WMABwclg+7ARAAuBHNp1GtDAPM6ilskl0mF/bRboOmCVdSfT50pBaOka2/
            EHu5izC8C1TOLlyiifdW3otksVj61K6wsc+tLu/d3Cip9fQ4XM04A93HyhBjzq8+
            oHo77XW+38auV1nef83QqILDmh5z9kvITOOlt3TBJWJv6mpBzatY5VMZxnxRsZfW
            bQ1PalS5Ti4OdRz8WXge6+fHaMTWVUFh4mczWtMH+jsv0iTwaPrPe8BVAo7juvog
            ZAZe9s2ntB2jZ3v0LleW6RNKxV+UtsrW2FRm3fYwduk3L/s/n3z9ecISBuvn/2iA
            SACKpPgzTU41lFpZeFXPup5OILQyjoPWYITY7S5bLmiHj4jggH7q82+GyjBmBhlt
            xI55Y02DiyfBtYp4NIweLdXeS+ULU746KjXZIQCB7ZubtJqx1sZs7GBIg96a5876
            dgPY/fVB438J+2FZL+MmNSE+NEkTbfYgYRGF0KraO3bvKuFabuKBVL/3mUK+nuy+
            qNnKFtawN6svDal/4Xxktv8m9IMaXEUlrqnmCODzUKsJ3NNFLIkZBuMGQn1Z+s7C
            IeAgLrkAo1bsBKFgZa7gm5ck3+wlnRw/AckRPWQ4CKJ5AgytN4yS/FPuD/jIp36b
            UQ7pKApVnqQMXr55NAU+CLR5Ed+cjgBU8OAEfHgF9DaB3+YU5zhRzPnclgxhmETU
            ZgEJAhUD4HBSZ9dNEwTiH2K3VQJTtVejSX54Hepm1Ihqyuu/FScmrOOBEIB0DYIM
            J43OK7s6a1z6hwvWzG/otNNruv4NnIz3Wmoc7/GMQrjffrJCZHClz5Fsa48zOw6S
            CjkyDzhUaQ==
            =only
            -----END PGP MESSAGE-----
          fp: E3CF3A557C3A53798EB3964606BAED053E44C047
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
