apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-secret
    namespace: cert-manager
data:
    apikey: ENC[AES256_GCM,data:ZGdY2ZVUHsrEXtuxwg3NOScuSBpj1vK8NRN6cp5WDxfKZIdTaQ4lym+owzkZV+47aYAFsQ==,iv:j3kVI+n5qiD1wvaOMCG6MZCjAXrHipdRf8GbMUg11aw=,tag:1SvNXIfoWeGhUe3eK45N9g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-19T11:46:49Z"
    mac: ENC[AES256_GCM,data:R9nKfE/tg9P1tyfdQo0iryWrFTtOlm/kO0FCRLt4JknbAcTQQMGUSirL/j9EHW2KqVRNmca+s74XqHiliMZfkpo+bjEhlyZWQp0t4KxuTaGITVbjg9rCKsyKHGETxhOfsJvI+J33VNd1XCGhXA65WTFPwbzfu2dCM+nHohVZ+oQ=,iv:hB0ewujkQ3qGZ4/9eUGUGRMjr+UXiH5PQvMnx42D0uc=,tag:YmCv8i0Ki80j43UM9l4oaQ==,type:str]
    pgp:
        - created_at: "2021-10-19T11:46:48Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA1WMABwclg+7ARAAuW9oae5Pc1+J/sUyM6ZctShXzyl0GxFe40HYXnUfgw5j
            JRDoh5KXmzcmjYbknBO18mx8GgbJvyvzrCd18yB3YwBML1YRpeCeYf7eHIrE1ow4
            tgUojtioGCAcCwnzWU1TK89e7ZqfPERSm49LV+KuJ5vMDJxTR8AtAsFTocge8mYg
            zLhtKYCE6aAQqnDOMjFLBahkerx+WClGtKwZu32H+Xhpgifn0Eaqk1tYHqcFbbLo
            Fv429MZaYdti2cpt70ZS+T74AA1luinuG+kbQFMN6OSxroQVq3zf/rg4xE2GMo6K
            KdxwMWWTsiBz9EJ8I7o1KOoGURSS/QsBWyDUigjz5UkAsDp+rdL/7QCoW2208vQk
            9R5nf6D26ANLAtwtovc2vbmnGtw60JYPoFBmUxANhmMYATMWTB4fLeYRiRdj0uAX
            6jqlwmGiHysS5AUTZ2OUK9pkXRDJvb8D19K7TU+659I6uYVBnmjO8jiJ7KufbSRZ
            VC9bm58jELkNTJw15mkMqlDQK/4vNfMisY8+eCLvqSf6bXVgJdiWF5DD/x0IAYnX
            qVzsFwOB4ZOh3jKBaVj4JRCYED2fhKEf33RAaob84M2n8GNLzia/ICpGyi3MLjqu
            doRH8EWHliB2jHmUV7mphfFJnhdK0RoFK+BMT54on+7x7rCaWZqVV+u6LiU468bU
            aAEJAhVbNWlDuz2ALYJod6gGsMunyEW7Mi4m7aavxma8gi7CywRI8/km2+G5Zr8x
            C64jBdJao5lUtZrKK25kQ/HpaxdioO4Lg9TPbRNtic+bFRushZXCawQ/okk6fj75
            LbaGgyHSp/mj
            =DcnN
            -----END PGP MESSAGE-----
          fp: E3CF3A557C3A53798EB3964606BAED053E44C047
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
