apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-crt
  namespace: cert-manager
spec:
  isCA: true
  commonName: self-signed-crt
  secretName: self-signed-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - "${DOMAIN}"
  - "*.${DOMAIN}"
  - "*.internal.${DOMAIN}"