---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 9.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  values:
    image:
      repository: nodered/node-red
      tag: 2.0.6-12-minimal
    env:
      TZ: America/Chicago
      NODE_RED_ENABLE_PROJECTS: "true"
    persistence:
      data:
        enabled: true
        storageClass: nfs-kube
        accessMode: ReadWriteOnce
        size: 1Gi
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "https://homer.${DOMAIN}"
        ingressClassName: internal
        tls:
        - hosts:
          - "red.internal.${DOMAIN}"
        hosts:
        - host: "red.internal.${DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
