---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: node-red
      version: 10.0.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
      # cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    # cleanupOnFail: true
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: storage
  values:
    image:
      repository: nodered/node-red
      tag: 2.2.2-12-minimal
    env:
      TZ: "${TIMEZONE}"
      NODE_RED_ENABLE_PROJECTS: "true"
    persistence:
      data:
        enabled: true
        storageClass: nfs-kube
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        tls:
        - hosts:
          - "red.internal.${DOMAIN}"
        hosts:
        - host: "red.internal.${DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
