---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-red
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  nfs:
    path: "${NFS_BASE_PATH}/Apps/node-red"
    server: "${NFS_SERVER_IP}"
  storageClassName: node-red
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red
  namespace: home
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: node-red
  volumeMode: Filesystem
