---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
  annotations: 
    fluxcd.io/automated: "false"
    filter.fluxcd.io/chart-image: semver:~v3.1.0
spec:
  releaseName: nfs-client-provisioner
  helmVersion: v3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/ 
    name: nfs-client-provisioner
    version: 1.2.9
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner-arm
      tag: v3.1.0-k8s1.11
    nfs:
      server: 192.168.1.105
      path: /export/k3s_nfs
    storageClass:
      name: nfs-kube
      reclaimPolicy: Retain
      defaultClass: true