apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs-kube
  namespace: kube-system
spec:
  chart: stable/nfs-client-provisioner
  version: 1.2.9
  targetNamespace: kube-system
  valuesContent: |-
    image:
      repository: quay.io/external_storage/nfs-client-provisioner-arm
      tag: v3.1.0-k8s1.11
    nfs:
      server: 192.168.1.105
      path: /export/k3s_nfs
    storageClass:
      name: nfs-kube
      reclaimPolicy: Retain
      defaultClass: true