---
name: flux-update-schedule
on:
  workflow_dispatch:
  schedule:
  - cron: "0 */6 * * *"
jobs:
  flux-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Flux CLI
      uses: fluxcd/flux2/action@main

    - name: Update Flux components
      id: update
      run: |
        UGLY_VERSION="$(flux -v)"
        VERSION="v${UGLY_VERSION#*flux version }"
        flux install \
          --version="${VERSION}" \
          --components=source-controller,kustomize-controller,helm-controller,notification-controller \
          --network-policy=false \
          --export > ./cluster/base/flux-system/gotk-components.yaml
        echo "::set-output name=flux_version::$VERSION"

    - name: Create pull request for Flux update
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "flux/update-${{ steps.update.outputs.flux_version }}"
        delete-branch: true
        title: "Update Flux components to ${{ steps.update.outputs.flux_version }}"
        signoff: true
        committer: "Richard Cox <6799456+RickCoxDev@users.noreply.github.com>"
        author: "Richard Cox <6799456+RickCoxDev@users.noreply.github.com>"
        assignees: "RickCoxDev"
        commit-message: "Update Flux components to ${{ steps.update.outputs.flux_version }}"
        body: |
          Release notes: https://github.com/fluxcd/flux2/releases/tag/${{ steps.update.outputs.flux_version }}
        labels: flux/update
