name: secrets
on:
  push:
    branches:
    - main
    paths:
    - "**.txt"
    - "**.env"
    - "!.env.sample"
env:
  DEBIAN_FRONTEND: "noninteractive"
  KUBECONFIG: "./kubeconfig"

jobs:
  sealed-secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Unlock secrets
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      run: |
        echo "$GIT_CRYPT_KEY" | base64 -d > ./git-crypt-key
        git-crypt unlock ./git-crypt-key
        rm ./git-crypt-key

    - name: Create secrets
      run: ./setup/generate-sealed-secrets.sh

    - name: Commit and push secrets
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config --global user.name "Richard Cox"
          git config --global user.email "6799456+RickCoxDev@users.noreply.github.com"
          git add cluster/_sealed-secrets.yml
          git commit -sm "Auto-update sealed-secrets" || exit 0
          git push
        fi

    - name: Apply secrets
      env:
        KUBECONFIG: ./kubconfig
      run: kubectl apply -f cluster/_sealed-secrets.yml
