---
name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: yamllint
        uses: frenck/action-yamllint@v1
        with:
          config: .github/linters/.yamllint.yaml

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: markdownlint
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          config_file: .github/linters/.markdownlint.yaml
          files: README.md
          ignore_files: ./github/*

  ansible-lint:
    name: ansible-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4.1.1
        with:
          args: '-c .github/linters/.ansible-lint.yaml'
