---
name: annotate-helm-releases
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
  - cron: '0 */6 * * *'
jobs:
  renovate-helm-releases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1

    - name: Renovate Helm Releases
      uses: k8s-at-home/renovate-helm-releases@v1.4.5
      with:
        cluster-path: "./cluster"

    - name: Create pull request for renovatebot helm-release annotations
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: renovate-annotations
        delete-branch: true
        title: "Update Renovate Annotations"
        signoff: true
        committer: "Richard Cox <6799456+RickCoxDev@users.noreply.github.com>"
        author: "Richard Cox <6799456+RickCoxDev@users.noreply.github.com>"
        assignees: "RickCoxDev"
        commit-message: "update renovate annotations"
        body: |
          Update HelmReleases inorder for Renovate to pick up new versions of Helm charts
        labels: renovate/annotations
