apiVersion: v1
kind: PersistentVolume
metadata:
  name: audiobooks
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  nfs:
    path: /export/AudioBooks
    server: 192.168.1.105
  storageClassName: manual
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobooks
  namespace: home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
  volumeMode: Filesystem
