---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: kube-system
spec:
  repo: https://charts.bitnami.com/bitnami
  chart: metallb
  version: 0.1.23
  valuesContent: |-
    controller:
      image:
        repository: metallb/controller
        tag: v0.9
    speaker:
      image:
        repository: metallb/speaker
        tag: v0.9
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 192.168.1.10/31
        - 192.168.1.12/30
        - 192.168.1.16/30
        - 192.168.1.20/32
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
        interval: 30s
      prometheusRule:
        enabled: false